### ISSUE TITLE
app icon not visible on windows

### ISSUE THREAD

**Issue by Haroenv** [jwronline/dashboard#27]
This is because there is no conversion made to `.ico`

**Comment by Haroenv** [comment]
Probably fixed in #28

**Comment by gaetanverbrugghe** [comment]
It has indeed been fixed.

![image](https://cloud.githubusercontent.com/assets/22528030/21150889/e594103e-c160-11e6-8f5b-62fa392319f8.png)

**Comment by Haroenv** [comment]
Thanks for confirming
